### ISSUE TITLE
XSS Vulnerability Issue

### ISSUE THREAD

**Issue by gaoxiaodiao** [akazwz/smail#12]
I really love this project, but I found a potential XSS vulnerability:

When I send the email below to the smail address:
<img width="667" alt="image" src="https://github.com/user-attachments/assets/6171ae01-1d57-4208-9614-f4c05c3f3f06">

It can trigger the `alert` function.
<img width="887" alt="image" src="https://github.com/user-attachments/assets/28572e86-b1c7-4d41-8436-db773df2d8c0">

I understand this project is in its early stages. It doesn’t matter if the issue can be resolved in the short term; I just want to bring attention to the **potential security issue.**

Finally, thanks to everyone who contributed to this project.

**Comment by akazwz** [comment]
@gaoxiaodiao Thank you for report this, the email content is show with iframe, I add sanbox: allow-script for the iframe. This should prevent any popups. Thank you very much
