### ISSUE TITLE
error executing a request on the primary: no such table: emails

### ISSUE THREAD

**Issue by baymax55** [akazwz/smail#2]
请问下我设置了`TURSO_DB_AUTH_TOKEN` 和 `TURSO_DB_URL`两个环境变量
然后只部署了email-worker进行测试
测试发送邮件时显示`emails`表不存在,请问是在什么时候自动创建这张表的呢,我是ts新手,谢谢

![image](https://github.com/akazwz/smail/assets/35788491/3c5d628a-de8c-4aa9-9e06-f9c9d4813d3e)

**Comment by akazwz** [comment]
@baymax55  需要手动执行的. 文件在 smail/packages/database/drizzle/0000_sturdy_arclight.sql

**Comment by baymax55** [comment]
非常感谢,我没有在turso网址上找到可以在线创建表,但我使用 `Turso CLI` 命令本地创建表成功了

> @baymax55 需要手动执行的. 文件在 smail/packages/database/drizzle/0000_sturdy_arclight.sql. 在 turso 上执行就可以
> 
> ```sql
> CREATE TABLE `emails` (
> 	`id` text PRIMARY KEY NOT NULL,
> 	`message_from` text NOT NULL,
> 	`message_to` text NOT NULL,
> 	`headers` text NOT NULL,
> 	`from` text NOT NULL,
> 	`sender` text,
> 	`reply_to` text,
> 	`delivered_to` text,
> 	`return_path` text,
> 	`to` text,
> 	`cc` text,
> 	`bcc` text,
> 	`subject` text,
> 	`message_id` text NOT NULL,
> 	`in_reply_to` text,
> 	`references` text,
> 	`date` text,
> 	`html` text,
> 	`text` text,
> 	`created_at` integer NOT NULL,
> 	`updated_at` integer NOT NULL
> );
> ```
