### ISSUE TITLE
worker没有触发

### ISSUE THREAD

**Issue by yesmore** [akazwz/smail#3]
按照说明配置后，客户端成功部署，生成临时邮箱，似乎能收到邮件，但是没有转发到worker，状态一直是“已删除”，是哪里配置不正确吗？
![667277b3c902cbae9fc4effd557b6149](https://github.com/akazwz/smail/assets/89140804/f4b56a8d-aeb4-48ff-bb5d-a70bf79c5129)
![1d5e5ae8ddbdafbf30e532a69fd75c4c](https://github.com/akazwz/smail/assets/89140804/b9f417b3-bf7a-4c6d-906f-51ebeef48833)
![cc1d819adedcec2f5917b8d3ea41ff31](https://github.com/akazwz/smail/assets/89140804/24d2650d-0338-41a8-9090-14520dfa4526)

域名是在cloudflare注册的
![e34cb5219fca0f0dd91a9996e05f87ac](https://github.com/akazwz/smail/assets/89140804/437d2d36-4c2d-4290-9c40-b8f53498f084)

**Comment by akazwz** [comment]
@yesmore cloudflare 展示 “已删除” 是正常的, 因为这个不是配置的转发地址. worker的指标也可能有延迟.  看你的描述似乎能收到邮件看起来应该是没问题的.  具体成功与否你可以去turso 数据库里看下. 落库了就是正常的.

**Comment by yesmore** [comment]
> @yesmore cloudflare 展示 “已删除” 是正常的, 因为这个不是配置的转发地址. worker的指标也可能有延迟.  看你的描述似乎能收到邮件看起来应该是没问题的.  具体成功与否你可以去turso 数据库里看下. 落库了就是正常的.

感谢回复(^🙏^)，数据库没有写入，主要是我看 worker 那里也没有请求记录，奇怪🤔

**Comment by yesmore** [comment]
监听到了日志，报错 LibsqlError: SQLITE_UNKNOWN: SQLite error: table emails has no column named cc

检查了一下是数据库少加了两个字段，成功接收了，感谢~
